version: '3.9'

services:
  server:
    image: 'nginx:latest'
    container_name: 'laravel_nginx_server'
    ports:
      - '8082:80'
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx/log:/var/log/nginx
      - ../src:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  php:
    build:
      context: ../dockerfiles
      dockerfile: php.dockerfile
    container_name: 'laravel_php'
    ports:
      - '3000:9000'
    volumes:
      - ../src:/var/www/html:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  mysql:
    image: mysql:latest
    container_name: 'laravel_mysql'
    env_file:
      - ../env/mysql.env
    ports:
      - '33062:3306'
    volumes:
    - db:/var/lib/mysql/
    networks:
      - net

networks:
  net:
    driver: "bridge"

volumes:
  db: