<?php

namespace App\Modules\Loan\Models;

use App\Modules\Loan\Scopes\LoanScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Loan extends Model
{
    protected $table = 'loans';

    protected $guarded = [];

    const STATUS_PENDING = 0;
    const STATUS_APPROVED = 1;
    const STATUS_REJECTED = 2;
    const STATUS_PAID = 3;

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new LoanScope());
    }

    /**
     * Retrieve the payments that belong to loan
     *
     * @return HasMany
     */
    public function repayments(): HasMany
    {
        return $this->hasMany(ScheduledRepayment::class);
    }
}