version: '3.9'

services:
  composer:
    build:
      context: ../dockerfiles
      dockerfile: ../dockerfiles/composer.dockerfile
    volumes:
      - ../../:/var/www/html
    networks:
      - net
