version: '3.9'

services:
  artisan:
    build:
      context: ../dockerfiles
      dockerfile: ../dockerfiles/php.dockerfile
    container_name: 'laravel_artisan'
    volumes:
      - ../../:/var/www/html
    entrypoint: ['php','/var/www/html/artisan']

    # all docker compose files must have same net work
    networks:
      - net
