version: '3.9'

services:
  server:
    image: 'nginx:latest'
    container_name: 'laravel_nginx_server'
    ports:
      - '8082:80'
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx/log:/var/log/nginx
      - ../../:/var/www/html
    networks:
      - net

  php:
    build:
      context: ../dockerfiles
      dockerfile: ../dockerfiles/php.dockerfile
    container_name: 'laravel_php'
    ports:
      - '3000:9000'
    volumes:
      - ../../:/var/www/html:delegated
      - ../php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    # add extra hosts just for linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  mysql:
    image: mysql:latest
    container_name: 'laravel_mysql'
    env_file:
      - ../env/mysql.env
    ports:
      - '33062:3306'
    volumes:
    - db:/var/lib/mysql/
    networks:
      - net

networks:
  net:
    driver: "bridge"

volumes:
  db: